on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - uses: actions/setup-python@v2
      - uses: taiki-e/install-action@v2
        with:
          python-version: 3.x
          tool: zola@0.17.1
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - run: bash build.sh
 
